# version: '3.8'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-bootcamp-app
    ports:
      - "8502:8501"
    environment:
      # Environment mode (development/production)
      - ENVIRONMENT=${ENVIRONMENT:-development}
      # OpenAI API Key (configure via .env file or Docker secrets)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Tavily API Key (configure via .env file or Docker secrets)
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
      # MCP Server URL (configure via .env file or Docker secrets)
      - MCP_SERVER_URL=${MCP_SERVER_URL:-}
      # Streamlit configuration
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      # Mount tmp directory for persistent uploads and cache
      - ./tmp:/app/tmp
      # Mount source code for development (optional - comment out for production)
      - .:/app
    # Uncomment to use Docker secrets (recommended for production)
    # secrets:
    #   - openai_api_key
    #   - tavily_api_key
    #   - mcp_server_url
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: MCP Server (FastMCP for prompt optimization)
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-bootcamp-mcp-server
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    # Uncomment to use Docker secrets (recommended for production)
    # secrets:
    #   - openai_api_key
    command: ["uv", "run", "python", "server.py"]
    restart: unless-stopped
    profiles:
      - mcp

volumes:
  tmp-data:
    driver: local

networks:
  default:
    name: llm-bootcamp-network

# Docker secrets configuration (uncomment for production use)
# To use secrets, create text files with your API keys:
#   echo "your-openai-key" > secrets/openai_api_key.txt
#   echo "your-tavily-key" > secrets/tavily_api_key.txt
#   echo "http://mcp-server:8000" > secrets/mcp_server_url.txt
# Then uncomment the secrets sections above and below
# secrets:
#   openai_api_key:
#     file: ./secrets/openai_api_key.txt
#   tavily_api_key:
#     file: ./secrets/tavily_api_key.txt
#   mcp_server_url:
#     file: ./secrets/mcp_server_url.txt
